
---
- name: To set GSLB Site Maintenance Mode
  hosts: localhost
  gather_facts: false

  vars:
    api: "gslbsiteops/maintenancemode"
    mode: false
    ansible_verbosity: 0
    ansible_deprecation_warnings: false
    ansible_command_warnings: false
    ansible_inventory_enabled: false

  vars_files:
    - vars/avi.yml


  tasks:
    - name: Set GSLB Site Maintenance Mode
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: post
        path: "{{ api }}"
        data:
          enabled: "{{ mode }}"
      register: avi_get_session_output
    
    - name: Print Debug
      ansible.builtin.debug:
        msg: "API Output: {{ avi_get_session_output.obj }}"
